---
- name: Deploy kinect app to minikube
  hosts: localhost
  tasks:
    # - name: delete previous frontend deployment
    #   shell: kubectl delete -f ../kubernetes-config/kinect-frontend.yaml

    # - name: delete previous backend deployment
    #   shell: kubectl delete -f ../kubernetes-config/kinect-backend.yaml

    # - name: delete previous secret
    #   shell: kubectl delete -f ../kubernetes-config/kinect-backend-secret.yaml

    - name: apply secret
      shell: kubectl apply -f ../kubernetes-config/kinect-backend-secret.yaml 

    - name: apply configmap
      shell: kubectl apply -f ../kubernetes-config/kinect-frontend-configmap.yaml 

    - name: apply ingress
    shell: kubectl apply -f ../kubernetes-config/kinect-ingress.yaml 

    - name: apply backend
      shell: kubectl apply -f ../kubernetes-config/kinect-backend.yaml

    - name: apply frontend
      shell: kubectl apply -f ../kubernetes-config/kinect-frontend.yaml
