---
- name: Deploy kinect app to minikube
  hosts: localhost
  connection: local
  become: true
  vars:
    ansible_python_interpreter: /var/lib/jenkins/workspace/kinect/venv/bin/python
  collections:
  collections:
    - community.kubernetes

  tasks:
  - name: Create minikube namespace
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: minikube

  - name: Apply secret
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config 
      # definition: "{{ lookup('file', '/home/ayushi/Desktop/sem2/spe/projects/KINECT--volunteer-matching-platform/kubernetes-config/kinect-backend-secret.yaml') }}"
      definition: "{{ lookup('file', '/var/lib/jenkins/workspace/kinect/kubernetes-config/kinect-backend-secret.yaml') }}"
      namespace: minikube

  - name: Apply configmap
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config 
      definition: "{{ lookup('file', '../kubernetes-config/kinect-frontend-configmap.yaml') }}"
      namespace: minikube

  - name: Apply ingress (if needed)
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config 
      definition: "{{ lookup('file', '../kubernetes-config/kinect-ingress.yaml') }}"
      namespace: minikube

  - name: Apply backend deployment
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config 
      definition: "{{ lookup('file', '../kubernetes-config/kinect-backend.yaml') }}"
      namespace: minikube

  - name: Apply frontend deployment
    k8s:
      state: present
      kubeconfig: /home/ayushi/.kube/config 
      definition: "{{ lookup('file', '../kubernetes-config/kinect-frontend.yaml') }}"
      namespace: minikube
